'use client'
import { DndContext, DragEndEvent, PointerSensor, useDroppable, useSensor, useSensors } from '@dnd-kit/core'
import { SortableContext, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import { GripVertical, Plus } from 'lucide-react'
import { useMemo, useState } from 'react'
import { Board, request, Task } from '@/lib/api'
import { TaskDrawer } from '@/components/task-drawer'

function Card({task,onOpen}:{task:Task;onOpen:()=>void}){ const {attributes,listeners,setNodeRef,transform,isDragging}=useSortable({id:task.id,data:{task}}); return <article ref={setNodeRef} style={{transform:CSS.Translate.toString(transform)}} {...attributes} className={`rounded-xl border border-[var(--line)] bg-[var(--panel)] p-4 shadow-sm ${isDragging?'opacity-60':''}`}><div className="mb-4 flex items-center justify-between"><button {...listeners} onClick={e=>e.stopPropagation()} className="-ml-2 rounded-lg p-1.5 muted hover:bg-black/5 dark:hover:bg-white/5" aria-label={`Drag ${task.identifier}`}><GripVertical size={16}/></button><span className="text-xs font-medium muted">{task.identifier}</span><span className={`h-2 w-2 rounded-full ${task.priority==='urgent'?'bg-red-500':task.priority==='high'?'bg-orange-500':task.priority==='medium'?'bg-amber-400':'bg-slate-300'}`} aria-label={`Priority ${task.priority}`}/></div><button onClick={onOpen} className="w-full text-left"><h3 className="text-sm font-medium leading-5">{task.title}</h3>{task.due_date&&<p className="mt-3 text-xs muted">Due {new Date(task.due_date).toLocaleDateString()}</p>}</button></article> }
function ColumnBox({id,name,tasks,onAdd,onOpen}:{id:string;name:string;tasks:Task[];onAdd:()=>void;onOpen:(task:Task)=>void}){ const {setNodeRef,isOver}=useDroppable({id}); return <section ref={setNodeRef} className={`min-h-[360px] w-[290px] shrink-0 rounded-2xl border border-[var(--line)] bg-black/[.025] p-3 dark:bg-white/[.025] ${isOver?'ring-2 ring-indigo-500/30':''}`}><div className="mb-3 flex items-center justify-between px-1"><div className="flex items-center gap-2"><h2 className="text-sm font-semibold">{name}</h2><span className="rounded-full bg-black/5 px-2 py-0.5 text-xs muted dark:bg-white/5">{tasks.length}</span></div><button onClick={onAdd} className="rounded-lg p-1 hover:bg-black/5 dark:hover:bg-white/5" aria-label={`Add task to ${name}`}><Plus size={16}/></button></div><SortableContext items={tasks.map(t=>t.id)} strategy={verticalListSortingStrategy}><div className="space-y-2">{tasks.map(t=><Card key={t.id} task={t} onOpen={()=>onOpen(t)}/>)}</div></SortableContext></section> }

export function KanbanBoard({initial,token,onChanged}:{initial:Board;token:string;onChanged:(b:Board)=>void}){
 const [creating,setCreating]=useState<string|null>(null); const [title,setTitle]=useState(''); const [selected,setSelected]=useState<Task|null>(null); const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:6}}));
 const byColumn=useMemo(()=>Object.fromEntries(initial.columns.map(c=>[c.id,initial.tasks.filter(t=>t.column_id===c.id).sort((a,b)=>a.position-b.position)])),[initial])
 async function add(columnId:string){ if(!title.trim()) return; const task=await request<Task>('/api/v1/tasks',{method:'POST',body:JSON.stringify({project_id:initial.project.id,column_id:columnId,title:title.trim()} )},token); onChanged({...initial,tasks:[...initial.tasks,task]}); setTitle(''); setCreating(null) }
 async function moved(e:DragEndEvent){ const task=e.active.data.current?.task as Task|undefined; if(!task||!e.over||String(e.over.id)===task.id) return; const overId=String(e.over.id); const target=initial.tasks.find(t=>t.id===overId); const destination=initial.columns.find(c=>c.id===overId)?.id ?? target?.column_id; if(!destination) return; const destinationTasks=(byColumn[destination]??[]).filter(t=>t.id!==task.id); let position=(destinationTasks.at(-1)?.position??0)+1000; if(target){const index=destinationTasks.findIndex(t=>t.id===target.id);const previous=index>0?destinationTasks[index-1]:undefined;position=previous?((previous.position+target.position)/2):target.position-1000} const optimistic={...task,column_id:destination,position,version:task.version+1}; onChanged({...initial,tasks:initial.tasks.map(t=>t.id===task.id?optimistic:t)}); try{ const updated=await request<Task>(`/api/v1/tasks/${task.id}/move`,{method:'POST',body:JSON.stringify({column_id:destination,position,version:task.version})},token); onChanged({...initial,tasks:initial.tasks.map(t=>t.id===task.id?updated:t)}); if(selected?.id===updated.id)setSelected(updated) }catch{ onChanged(initial) } }
 function updateTask(updated:Task){onChanged({...initial,tasks:initial.tasks.map(t=>t.id===updated.id?updated:t)});setSelected(updated)}
 return <><DndContext sensors={sensors} onDragEnd={moved}><div className="scrollbar flex gap-3 overflow-x-auto pb-4">{initial.columns.map(c=><ColumnBox key={c.id} id={c.id} name={c.name} tasks={byColumn[c.id]??[]} onAdd={()=>setCreating(c.id)} onOpen={setSelected}/>)}</div></DndContext>{creating&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/35 p-4" onMouseDown={()=>setCreating(null)}><div className="panel w-full max-w-md rounded-2xl p-5 shadow-soft" onMouseDown={e=>e.stopPropagation()}><h2 className="font-semibold">Create task</h2><input autoFocus value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>{if(e.key==='Enter') void add(creating)}} placeholder="What needs to be done?" className="mt-4 w-full rounded-xl border border-[var(--line)] bg-transparent px-3 py-3 outline-none"/><div className="mt-4 flex justify-end gap-2"><button onClick={()=>setCreating(null)} className="rounded-xl px-4 py-2 text-sm">Cancel</button><button onClick={()=>void add(creating)} className="rounded-xl bg-indigo-600 px-4 py-2 text-sm font-semibold text-white">Create</button></div></div></div>}{selected&&<TaskDrawer task={selected} token={token} onClose={()=>setSelected(null)} onUpdated={updateTask}/>}</>
}
