'use client'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { FormEvent, useEffect, useState } from 'react'
import { useAuth } from '@/components/providers'

export default function LoginPage(){
  const router=useRouter(); const {login,register,user}=useAuth();
  const [mode,setMode]=useState<'login'|'register'>('login'); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [nextPath,setNextPath]=useState('/app')
  useEffect(()=>{ const params=new URLSearchParams(window.location.search); if(params.get('mode')==='register') setMode('register'); const next=params.get('next'); if(next?.startsWith('/')&&!next.startsWith('//')) setNextPath(next) },[])
  useEffect(()=>{ if(user) router.replace(nextPath) },[user,router,nextPath])
  async function submit(e:FormEvent<HTMLFormElement>){ e.preventDefault(); setBusy(true); setError(''); const f=new FormData(e.currentTarget); try{ if(mode==='register') await register(String(f.get('name')),String(f.get('email')),String(f.get('password'))); else await login(String(f.get('email')),String(f.get('password'))); router.replace(nextPath) }catch(err){ setError(err instanceof Error?err.message:'Something went wrong') }finally{setBusy(false)} }
  return <main className="grid min-h-screen place-items-center px-6"><div className="w-full max-w-md"><Link href="/" className="mb-8 inline-flex items-center gap-2 font-semibold text-xl"><span className="grid h-9 w-9 place-items-center rounded-xl bg-indigo-600 text-white">T</span>TaskPilot</Link><div className="panel rounded-3xl p-7 shadow-soft"><h1 className="text-2xl font-semibold">{mode==='login'?'Welcome back':'Create your workspace'}</h1><p className="mt-2 text-sm muted">{mode==='login'?'Pick up where your team left off.':'Start with a personal workspace and grow from there.'}</p><form onSubmit={submit} className="mt-7 space-y-4">{mode==='register'&&<label className="block text-sm font-medium">Name<input required name="name" minLength={2} className="mt-2 w-full rounded-xl border border-[var(--line)] bg-transparent px-3 py-3 outline-none focus:border-indigo-500"/></label>}<label className="block text-sm font-medium">Email<input required type="email" name="email" className="mt-2 w-full rounded-xl border border-[var(--line)] bg-transparent px-3 py-3 outline-none focus:border-indigo-500"/></label><label className="block text-sm font-medium">Password<input required type="password" name="password" minLength={10} className="mt-2 w-full rounded-xl border border-[var(--line)] bg-transparent px-3 py-3 outline-none focus:border-indigo-500"/></label>{error&&<p role="alert" className="rounded-xl bg-red-500/10 p-3 text-sm text-red-600">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-indigo-600 px-4 py-3 font-semibold text-white disabled:opacity-50">{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button></form><button onClick={()=>setMode(mode==='login'?'register':'login')} className="mt-5 w-full text-sm muted hover:text-[var(--text)]">{mode==='login'?'New to TaskPilot? Create an account':'Already have an account? Sign in'}</button></div></div></main>
}
