'use client'

import { useQuery } from '@tanstack/react-query'
import { ArrowLeft, KeyRound, Laptop, MailCheck, ShieldCheck, Trash2 } from 'lucide-react'
import Link from 'next/link'
import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'

import { useAuth } from '@/components/providers'
import { ThemeToggle } from '@/components/theme-toggle'
import { request } from '@/lib/api'

type Account={id:string;email:string;name:string;email_verified:boolean;email_verified_at:string|null}
type Session={id:string;device_name:string|null;ip_address:string|null;user_agent:string|null;last_used_at:string;created_at:string;expires_at:string;revoked_at:string|null;active:boolean;current:boolean}
type TokenResponse={message:string;development_token?:string}

export default function AccountSettingsPage(){
 const {token,loading,logout}=useAuth();const router=useRouter();const [message,setMessage]=useState('');const [error,setError]=useState('');const [devLink,setDevLink]=useState('')
 useEffect(()=>{if(!loading&&!token)router.replace('/login')},[loading,token,router])
 const account=useQuery({queryKey:['account-status'],queryFn:()=>request<Account>('/api/v1/auth/account',{},token),enabled:!!token})
 const sessions=useQuery({queryKey:['account-sessions'],queryFn:()=>request<Session[]>('/api/v1/auth/sessions',{},token),enabled:!!token})
 function clear(){setMessage('');setError('');setDevLink('')}
 async function verify(){clear();try{const result=await request<TokenResponse>('/api/v1/auth/email-verification/request',{method:'POST'},token);setMessage(result.message);if(result.development_token)setDevLink(`/verify-email?token=${encodeURIComponent(result.development_token)}`)}catch(err){setError(err instanceof Error?err.message:'Could not request verification')}}
 async function changePassword(event:FormEvent<HTMLFormElement>){event.preventDefault();clear();const f=new FormData(event.currentTarget);const current_password=String(f.get('current_password')??'');const new_password=String(f.get('new_password')??'');const confirm=String(f.get('confirm')??'');if(new_password!==confirm){setError('New passwords do not match.');return}try{await request('/api/v1/auth/change-password',{method:'POST',body:JSON.stringify({current_password,new_password})},token);setMessage('Password changed. All sessions were signed out.');await logout();router.replace('/login')}catch(err){setError(err instanceof Error?err.message:'Could not change password')}}
 async function changeEmail(event:FormEvent<HTMLFormElement>){event.preventDefault();clear();const f=new FormData(event.currentTarget);try{const result=await request<TokenResponse>('/api/v1/auth/change-email',{method:'POST',body:JSON.stringify({password:String(f.get('password')??''),email:String(f.get('email')??'')})},token);setMessage(result.message);if(result.development_token)setDevLink(`/confirm-email?token=${encodeURIComponent(result.development_token)}`);event.currentTarget.reset()}catch(err){setError(err instanceof Error?err.message:'Could not request email change')}}
 async function revoke(id:string){clear();try{await request(`/api/v1/auth/sessions/${id}`,{method:'DELETE'},token);await sessions.refetch();setMessage('Device signed out.')}catch(err){setError(err instanceof Error?err.message:'Could not revoke session')}}
 async function logoutAll(){clear();try{await request('/api/v1/auth/sessions/logout-all',{method:'POST'},token);await logout();router.replace('/login')}catch(err){setError(err instanceof Error?err.message:'Could not sign out devices')}}
 async function deleteAccount(event:FormEvent<HTMLFormElement>){event.preventDefault();clear();const f=new FormData(event.currentTarget);try{await request('/api/v1/auth/delete-account',{method:'POST',body:JSON.stringify({password:String(f.get('password')??''),confirmation:String(f.get('confirmation')??'')})},token);await logout();router.replace('/login')}catch(err){setError(err instanceof Error?err.message:'Could not delete account')}}
 if(loading||!token)return <div className="grid min-h-screen place-items-center muted">Loading TaskPilot…</div>
 return <main className="min-h-screen bg-[var(--bg)]"><header className="border-b border-[var(--line)] bg-[var(--panel)]"><div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-4 sm:px-6"><div className="flex items-center gap-3"><Link href="/app" className="rounded-xl border border-[var(--line)] p-2"><ArrowLeft size={18}/></Link><div><p className="text-xs muted">Settings</p><h1 className="font-semibold">Account & security</h1></div></div><ThemeToggle/></div></header><div className="mx-auto max-w-5xl space-y-5 p-4 sm:p-6">{message&&<div className="rounded-2xl bg-emerald-500/10 p-4 text-sm text-emerald-700 dark:text-emerald-300">{message}{devLink&&<Link href={devLink} className="ml-2 font-semibold underline">Open development confirmation</Link>}</div>}{error&&<div role="alert" className="rounded-2xl bg-red-500/10 p-4 text-sm text-red-600">{error}</div>}
 <section className="panel rounded-2xl p-5"><div className="flex items-start gap-3"><MailCheck className="mt-0.5 text-indigo-600"/><div className="min-w-0 flex-1"><h2 className="font-semibold">Email verification</h2><p className="mt-1 text-sm muted">{account.data?.email??'Loading…'}</p><div className="mt-3 flex flex-wrap items-center gap-3"><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${account.data?.email_verified?'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300':'bg-amber-500/10 text-amber-700 dark:text-amber-300'}`}>{account.data?.email_verified?'Verified':'Not verified'}</span>{!account.data?.email_verified&&<button onClick={()=>void verify()} className="rounded-xl border border-[var(--line)] px-3 py-2 text-sm">Send verification email</button>}</div></div></div></section>
 <section className="grid gap-5 lg:grid-cols-2"><form onSubmit={changePassword} className="panel rounded-2xl p-5"><div className="flex items-center gap-2"><KeyRound size={18}/><h2 className="font-semibold">Change password</h2></div><p className="mt-2 text-sm muted">Changing your password signs out every device.</p><input required type="password" name="current_password" placeholder="Current password" className="mt-4 w-full rounded-xl border border-[var(--line)] bg-transparent px-3 py-3 text-sm"/><input required minLength={10} type="password" name="new_password" placeholder="New password" className="mt-3 w-full rounded-xl border border-[var(--line)] bg-transparent px-3 py-3 text-sm"/><input required minLength={10} type="password" name="confirm" placeholder="Confirm new password" className="mt-3 w-full rounded-xl border border-[var(--line)] bg-transparent px-3 py-3 text-sm"/><button className="mt-4 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Update password</button></form><form onSubmit={changeEmail} className="panel rounded-2xl p-5"><div className="flex items-center gap-2"><ShieldCheck size={18}/><h2 className="font-semibold">Change email</h2></div><p className="mt-2 text-sm muted">The new address must be confirmed before it replaces your current email.</p><input required type="email" name="email" placeholder="New email address" className="mt-4 w-full rounded-xl border border-[var(--line)] bg-transparent px-3 py-3 text-sm"/><input required type="password" name="password" placeholder="Current password" className="mt-3 w-full rounded-xl border border-[var(--line)] bg-transparent px-3 py-3 text-sm"/><button className="mt-4 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Send confirmation</button></form></section>
 <section className="panel rounded-2xl p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Laptop size={18}/><h2 className="font-semibold">Devices & sessions</h2></div><p className="mt-1 text-sm muted">Review active and historical sessions. Refresh tokens remain hashed and rotate on refresh.</p></div><button onClick={()=>void logoutAll()} className="rounded-xl border border-red-300/50 px-3 py-2 text-sm text-red-600">Sign out all devices</button></div><div className="mt-4 divide-y divide-[var(--line)]">{sessions.data?.map(session=><div key={session.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div className="min-w-0"><p className="text-sm font-medium">{session.device_name||'Browser session'} {session.current&&<span className="ml-2 rounded-full bg-indigo-500/10 px-2 py-0.5 text-[11px] text-indigo-600">Current</span>}</p><p className="mt-1 text-xs muted">{session.ip_address||'Unknown network'} · Last used {new Date(session.last_used_at).toLocaleString()}</p><p className="mt-1 max-w-2xl truncate text-[11px] muted">{session.user_agent||'No user agent recorded'}</p></div>{session.active?<button onClick={()=>void revoke(session.id)} className="rounded-xl border border-[var(--line)] px-3 py-2 text-xs">Sign out</button>:<span className="text-xs muted">Revoked/expired</span>}</div>)}{sessions.isLoading&&<p className="py-5 text-sm muted">Loading sessions…</p>}</div></section>
 <section className="panel rounded-2xl p-5"><h2 className="font-semibold">Workspace settings</h2><p className="mt-1 text-sm muted">Manage workspace membership, invitations, ownership and lifecycle separately.</p><Link href="/app/settings/workspaces" className="mt-4 inline-block rounded-xl border border-[var(--line)] px-3 py-2 text-sm">Open workspace settings</Link></section>
 <form onSubmit={deleteAccount} className="rounded-2xl border border-red-300/40 bg-red-500/[.035] p-5"><div className="flex items-center gap-2 text-red-600"><Trash2 size={18}/><h2 className="font-semibold">Delete account</h2></div><p className="mt-2 text-sm muted">Your account is anonymized and sessions are revoked. Transfer or delete workspaces/projects you own first.</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><input required type="password" name="password" placeholder="Current password" className="rounded-xl border border-[var(--line)] bg-transparent px-3 py-3 text-sm"/><input required name="confirmation" placeholder="Type DELETE" pattern="DELETE" className="rounded-xl border border-[var(--line)] bg-transparent px-3 py-3 text-sm"/></div><button className="mt-4 rounded-xl bg-red-600 px-4 py-2.5 text-sm font-semibold text-white">Delete my account</button></form>
 </div></main>
}
