import Link from 'next/link'
import { ArrowRight, CheckCircle2, Layers3, Radio, Search, ShieldCheck } from 'lucide-react'

export default function Landing(){
  return <main className="min-h-screen overflow-hidden">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><div className="flex items-center gap-2 font-semibold text-xl"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-indigo-500 to-violet-600 text-white">T</span>TaskPilot</div><nav className="flex items-center gap-3"><Link href="/login" className="rounded-xl px-4 py-2 text-sm font-medium">Sign in</Link><Link href="/login?mode=register" className="rounded-xl bg-[var(--text)] px-4 py-2 text-sm font-semibold text-[var(--bg)]">Start free</Link></nav></header>
    <section className="mx-auto grid max-w-7xl gap-14 px-6 pb-24 pt-20 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div><span className="inline-flex rounded-full border border-[var(--line)] bg-[var(--panel)] px-3 py-1 text-sm muted">Plan clearly. Ship confidently.</span><h1 className="mt-6 max-w-3xl text-5xl font-semibold tracking-[-.045em] sm:text-7xl">One calm place for work that keeps moving.</h1><p className="mt-6 max-w-2xl text-lg leading-8 muted">Projects, boards, deadlines, comments, and realtime team activity without turning your workspace into noise.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/login?mode=register" className="inline-flex items-center gap-2 rounded-2xl bg-indigo-600 px-5 py-3 font-semibold text-white shadow-soft">Create your workspace <ArrowRight size={18}/></Link><Link href="/login" className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] px-5 py-3 font-semibold">Sign in</Link></div><div className="mt-10 grid max-w-xl grid-cols-2 gap-4 text-sm muted"><span className="flex gap-2"><ShieldCheck size={18}/>Server-side permissions</span><span className="flex gap-2"><Radio size={18}/>Realtime updates</span><span className="flex gap-2"><Search size={18}/>Workspace search roadmap</span><span className="flex gap-2"><CheckCircle2 size={18}/>Optimistic board moves</span></div></div>
    <div className="relative"><div className="absolute -inset-10 -z-10 rounded-full bg-indigo-500/10 blur-3xl"/><div className="panel rounded-[28px] p-4 shadow-soft"><div className="mb-4 flex items-center justify-between px-2"><div><p className="text-sm muted">Website Redesign</p><h2 className="font-semibold">Sprint board</h2></div><div className="flex -space-x-2">{['ME','SA','AL'].map(x=><span key={x} className="grid h-8 w-8 place-items-center rounded-full border-2 border-[var(--panel)] bg-slate-200 text-[10px] font-bold text-slate-700">{x}</span>)}</div></div><div className="grid gap-3 md:grid-cols-3">{[['To Do','Audit landing page','TP-24'],['In Progress','Realtime board sync','TP-28'],['Review','Mobile task details','TP-31']].map(([col,title,id])=><div key={id} className="rounded-2xl bg-black/[.035] p-3 dark:bg-white/[.035]"><p className="mb-3 text-xs font-semibold uppercase tracking-wider muted">{col}</p><div className="rounded-xl border border-[var(--line)] bg-[var(--panel)] p-4"><Layers3 size={16} className="mb-7 muted"/><p className="font-medium">{title}</p><p className="mt-2 text-xs muted">{id}</p></div></div>)}</div></div></div></section>
  </main>
}
