'use client'

import { useQuery } from '@tanstack/react-query'
import { ArrowLeft, Copy, KeyRound, PlugZap, RefreshCcw, Trash2 } from 'lucide-react'
import Link from 'next/link'
import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'

import { useAuth } from '@/components/providers'
import { ThemeToggle } from '@/components/theme-toggle'
import { request, Workspace } from '@/lib/api'

type ApiToken={id:string;name:string;prefix:string;scopes:string[];expires_at:string|null;last_used_at:string|null;revoked_at:string|null;created_at:string;token?:string}
type Webhook={id:string;workspace_id:string;name:string;url:string;events:string[];active:boolean;created_at:string;updated_at:string;secret?:string}
type Delivery={id:string;activity_id:string;event:string;status:string;attempts:number;response_status:number|null;last_error:string|null;next_attempt_at:string|null;delivered_at:string|null;created_at:string}

export default function IntegrationsPage(){
  const {token,loading}=useAuth();const router=useRouter();const [workspaceId,setWorkspaceId]=useState('');const [message,setMessage]=useState('');const [error,setError]=useState('');const [revealed,setRevealed]=useState('');const [deliveryHook,setDeliveryHook]=useState('')
  useEffect(()=>{if(!loading&&!token)router.replace('/login')},[loading,token,router])
  const workspaces=useQuery({queryKey:['workspaces'],queryFn:()=>request<Workspace[]>('/api/v1/workspaces',{},token),enabled:!!token})
  useEffect(()=>{if(!workspaceId&&workspaces.data?.[0])setWorkspaceId(workspaces.data[0].id)},[workspaceId,workspaces.data])
  const tokens=useQuery({queryKey:['api-tokens'],queryFn:()=>request<ApiToken[]>('/api/v1/integrations/tokens',{},token),enabled:!!token})
  const webhooks=useQuery({queryKey:['webhooks',workspaceId],queryFn:()=>request<Webhook[]>(`/api/v1/workspaces/${workspaceId}/webhooks`,{},token),enabled:!!token&&!!workspaceId,retry:false})
  const deliveries=useQuery({queryKey:['webhook-deliveries',workspaceId,deliveryHook],queryFn:()=>request<Delivery[]>(`/api/v1/workspaces/${workspaceId}/webhooks/${deliveryHook}/deliveries`,{},token),enabled:!!token&&!!workspaceId&&!!deliveryHook,retry:false})
  function reset(){setMessage('');setError('');setRevealed('')}
  async function createToken(e:FormEvent<HTMLFormElement>){e.preventDefault();reset();const f=new FormData(e.currentTarget);try{const result=await request<ApiToken>('/api/v1/integrations/tokens',{method:'POST',body:JSON.stringify({name:String(f.get('name')??''),scopes:f.get('write')?['read','write']:['read'],expires_at:null})},token);setRevealed(result.token??'');setMessage('API token created. Copy it now; it will not be shown again.');e.currentTarget.reset();await tokens.refetch()}catch(err){setError(err instanceof Error?err.message:'Could not create API token')}}
  async function revokeToken(id:string){reset();if(!window.confirm('Revoke this API token? Existing clients using it will stop working.'))return;try{await request(`/api/v1/integrations/tokens/${id}`,{method:'DELETE'},token);setMessage('API token revoked.');await tokens.refetch()}catch(err){setError(err instanceof Error?err.message:'Could not revoke token')}}
  async function createWebhook(e:FormEvent<HTMLFormElement>){e.preventDefault();reset();if(!workspaceId)return;const f=new FormData(e.currentTarget);const events=String(f.get('events')??'*').split(',').map(v=>v.trim()).filter(Boolean);try{const result=await request<Webhook>(`/api/v1/workspaces/${workspaceId}/webhooks`,{method:'POST',body:JSON.stringify({name:String(f.get('name')??''),url:String(f.get('url')??''),events})},token);setRevealed(result.secret??'');setMessage('Webhook created. Copy the signing secret now; it will not be shown again.');e.currentTarget.reset();await webhooks.refetch()}catch(err){setError(err instanceof Error?err.message:'Could not create webhook')}}
  async function toggleWebhook(item:Webhook){reset();try{await request(`/api/v1/workspaces/${workspaceId}/webhooks/${item.id}`,{method:'PATCH',body:JSON.stringify({active:!item.active})},token);await webhooks.refetch()}catch(err){setError(err instanceof Error?err.message:'Could not update webhook')}}
  async function rotate(item:Webhook){reset();if(!window.confirm(`Rotate the signing secret for ${item.name}?`))return;try{const result=await request<{secret:string}>(`/api/v1/workspaces/${workspaceId}/webhooks/${item.id}/rotate-secret`,{method:'POST'},token);setRevealed(result.secret);setMessage('Webhook secret rotated. Copy the new secret now.')}catch(err){setError(err instanceof Error?err.message:'Could not rotate secret')}}
  async function removeWebhook(item:Webhook){reset();if(!window.confirm(`Delete webhook ${item.name}?`))return;try{await request(`/api/v1/workspaces/${workspaceId}/webhooks/${item.id}`,{method:'DELETE'},token);if(deliveryHook===item.id)setDeliveryHook('');await webhooks.refetch()}catch(err){setError(err instanceof Error?err.message:'Could not delete webhook')}}
  async function copySecret(){if(revealed)await navigator.clipboard.writeText(revealed)}
  if(loading||!token)return <div className="grid min-h-screen place-items-center muted">Loading TaskPilot…</div>
  return <main className="min-h-screen bg-[var(--bg)]"><header className="border-b border-[var(--line)] bg-[var(--panel)]"><div className="mx-auto flex h-16 max-w-5xl items-center justify-between px-4 sm:px-6"><div className="flex items-center gap-3"><Link href="/app" className="rounded-xl border border-[var(--line)] p-2"><ArrowLeft size={18}/></Link><div><p className="text-xs muted">Settings</p><h1 className="font-semibold">Integrations</h1></div></div><ThemeToggle/></div></header><div className="mx-auto max-w-5xl space-y-5 p-4 sm:p-6">
    {message&&<div className="rounded-2xl bg-emerald-500/10 p-4 text-sm text-emerald-700 dark:text-emerald-300">{message}</div>}{error&&<div className="rounded-2xl bg-red-500/10 p-4 text-sm text-red-600">{error}</div>}{revealed&&<div className="rounded-2xl border border-amber-400/40 bg-amber-500/[.06] p-4"><p className="text-xs font-semibold uppercase tracking-wider text-amber-700 dark:text-amber-300">Shown once</p><div className="mt-2 flex items-center gap-2"><code className="min-w-0 flex-1 overflow-x-auto rounded-xl bg-black/5 px-3 py-2 text-xs dark:bg-white/5">{revealed}</code><button onClick={()=>void copySecret()} className="rounded-xl border border-[var(--line)] p-2" aria-label="Copy secret"><Copy size={16}/></button></div></div>}
    <section className="grid gap-5 lg:grid-cols-2"><form onSubmit={createToken} className="panel rounded-2xl p-5"><div className="flex items-center gap-2"><KeyRound size={18}/><h2 className="font-semibold">Personal API token</h2></div><p className="mt-2 text-sm muted">Use Bearer tokens for scripts and API clients. Tokens are stored only as SHA-256 hashes.</p><input required name="name" maxLength={120} placeholder="CI script" className="mt-4 w-full rounded-xl border border-[var(--line)] bg-transparent px-3 py-3 text-sm"/><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" name="write"/>Allow write operations</label><button className="mt-4 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Create token</button></form><div className="panel rounded-2xl p-5"><h2 className="font-semibold">Your API tokens</h2><div className="mt-3 divide-y divide-[var(--line)]">{tokens.data?.map(item=><div key={item.id} className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="text-sm font-medium">{item.name}</p><p className="text-xs muted">{item.prefix}… · {item.scopes.join(', ')} · {item.last_used_at?`used ${new Date(item.last_used_at).toLocaleString()}`:'never used'}</p></div>{item.revoked_at?<span className="text-xs muted">Revoked</span>:<button onClick={()=>void revokeToken(item.id)} className="rounded-lg border border-red-500/30 p-2 text-red-600" aria-label="Revoke token"><Trash2 size={15}/></button>}</div>)}{tokens.isLoading&&<p className="py-4 text-sm muted">Loading tokens…</p>}{tokens.data?.length===0&&<p className="py-4 text-sm muted">No API tokens yet.</p>}</div></div></section>
    <section className="panel rounded-2xl p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="flex items-center gap-2"><PlugZap size={18}/><h2 className="font-semibold">Workspace webhooks</h2></div><p className="mt-1 text-sm muted">Signed JSON events with automatic retries. Owner/admin permissions are required.</p></div><label className="text-xs muted">Workspace<select value={workspaceId} onChange={e=>{setWorkspaceId(e.target.value);setDeliveryHook('')}} className="mt-1 block rounded-xl border border-[var(--line)] bg-[var(--panel)] px-3 py-2 text-sm text-[var(--fg)]">{workspaces.data?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><form onSubmit={createWebhook} className="mt-5 grid gap-3 lg:grid-cols-[1fr_1.5fr_1fr_auto]"><input required name="name" placeholder="Deployment events" className="rounded-xl border border-[var(--line)] bg-transparent px-3 py-3 text-sm"/><input required type="url" name="url" placeholder="https://example.com/taskpilot" className="rounded-xl border border-[var(--line)] bg-transparent px-3 py-3 text-sm"/><input name="events" defaultValue="task.*" placeholder="task.*,comment.*" className="rounded-xl border border-[var(--line)] bg-transparent px-3 py-3 text-sm"/><button className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Add</button></form><div className="mt-5 divide-y divide-[var(--line)]">{webhooks.data?.map(item=><div key={item.id} className="grid gap-3 py-4 md:grid-cols-[1fr_auto]"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-medium">{item.name}</p><span className={`rounded-full px-2 py-0.5 text-[11px] ${item.active?'bg-emerald-500/10 text-emerald-600':'bg-black/5 muted dark:bg-white/5'}`}>{item.active?'Active':'Paused'}</span></div><p className="mt-1 break-all text-xs muted">{item.url}</p><p className="mt-1 text-xs muted">Events: {item.events.join(', ')}</p></div><div className="flex flex-wrap items-center gap-2"><button onClick={()=>setDeliveryHook(deliveryHook===item.id?'':item.id)} className="rounded-lg border border-[var(--line)] px-2.5 py-1.5 text-xs">Deliveries</button><button onClick={()=>void toggleWebhook(item)} className="rounded-lg border border-[var(--line)] px-2.5 py-1.5 text-xs">{item.active?'Pause':'Enable'}</button><button onClick={()=>void rotate(item)} className="rounded-lg border border-[var(--line)] p-2" aria-label="Rotate secret"><RefreshCcw size={14}/></button><button onClick={()=>void removeWebhook(item)} className="rounded-lg border border-red-500/30 p-2 text-red-600" aria-label="Delete webhook"><Trash2 size={14}/></button></div></div>)}{webhooks.isError&&<p className="py-4 text-sm text-amber-700 dark:text-amber-300">You may need workspace owner/admin access to manage webhooks.</p>}{webhooks.data?.length===0&&<p className="py-4 text-sm muted">No webhooks for this workspace.</p>}</div></section>
    {deliveryHook&&<section className="panel rounded-2xl p-5"><h2 className="font-semibold">Recent webhook deliveries</h2><div className="mt-3 divide-y divide-[var(--line)]">{deliveries.data?.map(item=><div key={item.id} className="grid gap-2 py-3 sm:grid-cols-[1fr_auto]"><div><p className="text-sm font-medium">{item.event}</p><p className="text-xs muted">{item.status} · {item.attempts} attempt{item.attempts===1?'':'s'}{item.response_status?` · HTTP ${item.response_status}`:''}{item.last_error?` · ${item.last_error}`:''}</p></div><time className="text-xs muted">{new Date(item.created_at).toLocaleString()}</time></div>)}{deliveries.isLoading&&<p className="py-4 text-sm muted">Loading deliveries…</p>}{deliveries.data?.length===0&&<p className="py-4 text-sm muted">No deliveries yet.</p>}</div></section>}
  </div></main>
}
